- hosts: localhost
  user: ansible
  become: true
  gather_facts: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  vars_files:
    - "vars/main.yml"

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/directories.yml
    - include: tasks/packages.yml
    - include: tasks/non-packages.yml
    - include: tasks/pips.yml
    - include: tasks/flatpaks.yml
